// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXC6mrJhUqfF_dH2AriCdkS2ggurYKfIc',
    appId: '1:471848772810:web:59e1a3cfc05b21d8b34033',
    messagingSenderId: '471848772810',
    projectId: 'mis-lab3-cf789',
    authDomain: 'mis-lab3-cf789.firebaseapp.com',
    storageBucket: 'mis-lab3-cf789.appspot.com',
    measurementId: 'G-EN635W9LPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx8dRgbMsaQYbV6OGJZHSurFUjaCsxNBc',
    appId: '1:471848772810:android:1cd6bd8b7a001b67b34033',
    messagingSenderId: '471848772810',
    projectId: 'mis-lab3-cf789',
    storageBucket: 'mis-lab3-cf789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ_1efGvq5m6BdI_vtGk8nvjsb25UKOOA',
    appId: '1:471848772810:ios:a2f8c6bd6d96478db34033',
    messagingSenderId: '471848772810',
    projectId: 'mis-lab3-cf789',
    storageBucket: 'mis-lab3-cf789.appspot.com',
    iosBundleId: 'com.example.mislab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ_1efGvq5m6BdI_vtGk8nvjsb25UKOOA',
    appId: '1:471848772810:ios:a0c6b965bdaf01cfb34033',
    messagingSenderId: '471848772810',
    projectId: 'mis-lab3-cf789',
    storageBucket: 'mis-lab3-cf789.appspot.com',
    iosBundleId: 'com.example.mislab3.RunnerTests',
  );
}
